### ISSUE TITLE
进度条自定义问题

### ISSUE THREAD

**Issue by Joshuapenggit** [tosmart01/fastsql#1]
多张表进行迁移，是否可以对进度条进行标示，如将进度条名称修改为对应表名
<img width="880" alt="WeChat5e271b88ce68d39794b2f008d714518a" src="https://user-images.githubusercontent.com/46835574/80372430-18407100-88c6-11ea-9d90-da2de2ad728c.png">

**Comment by tosmart01** [comment]
pip install fast_sql==1.2.22
添加desc 参数，手动指定进度信息
